FROM ubuntu:14.04 
MAINTAINER Thomas Ridings
RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list 
RUN apt-get updateRUN apt-get install -y python-software-properties curl git
RUN add-apt-repository -y ppa:chris-lea/node.js
RUN apt-get -qq update 
RUN apt-get install -y nodejs 
RUN npm install -g express jade body-parser errorhandler watson-developer-cloud-alpha mongodb monk 
EXPOSE 3000 
ADD start.sh /start.sh 
RUN chmod +x /start.sh 
CMD ["/start.sh"]